[tool.poetry]
name = "chatgse"
version = "0.2.18"
description = "Gene set interpretation assisted by Large Language Models and more"
authors = ["Sebastian Lobentanzer <sebastian.lobentanzer@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
openai = "^0.27.4"
streamlit = "^1.21.0"
pandas = "~1.5"
tabulate = "^0.9.0"
loguru = "^0.7.0"
langchain = "^0.0.146"
huggingface-hub = "^0.14.1"
redis = "^4.5.4"
retry = "^0.9.2"
tiktoken = "^0.4.0"
pytest = "^7.3.1"
pymilvus = "^2.2.8"
pymupdf = "^1.22.3"
text2term = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
